sudo: required
services:
  - docker

script:
  - docker build -t larlon/elm .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push larlon/elm;
    fi
